//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.person;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import com.miicaa.home.data.business.org.UserInfo;
import com.yxst.epic.yixin.preference.CachePrefs_;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PersonHome_
    extends PersonHome
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String M_USER_CODE_EXTRA = "mUserCode";
    public final static String TITLE_TEXT_EXTRA = "titleText";
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.person_home_activity);
    }

    private void init_(Bundle savedInstanceState) {
        mCachePrefs = new CachePrefs_(this);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PersonHome_.IntentBuilder_ intent(Context context) {
        return new PersonHome_.IntentBuilder_(context);
    }

    public static PersonHome_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PersonHome_.IntentBuilder_(fragment);
    }

    public static PersonHome_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PersonHome_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mMsgButton = ((Button) hasViews.findViewById(id.frame_me_id_send_msg));
        mUserText = ((TextView) hasViews.findViewById(id.nameTextView));
        mCallButton = ((Button) hasViews.findViewById(id.person_home_id_call_phone));
        mTitleText = ((TextView) hasViews.findViewById(id.person_home_id_user_title));
        mDynamicButton = ((Button) hasViews.findViewById(id.person_home_id_dynamic));
        mEmailButton = ((Button) hasViews.findViewById(id.frame_me_id_send_email));
        mOtherLayout = ((LinearLayout) hasViews.findViewById(id.person_home_id_other_layout));
        mWorkButton = ((Button) hasViews.findViewById(id.person_home_id_work));
        talkButton = ((Button) hasViews.findViewById(id.personHomeTalk));
        button = ((Button) hasViews.findViewById(id.person_home_id_back));
        mUserHeadImg = ((ImageView) hasViews.findViewById(id.headImageView));
        {
            View view = hasViews.findViewById(id.headImageView);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PersonHome_.this.headViewClick(view);
                    }

                }
                );
            }
        }
        crateData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(M_USER_CODE_EXTRA)) {
                mUserCode = extras_.getString(M_USER_CODE_EXTRA);
            }
            if (extras_.containsKey(TITLE_TEXT_EXTRA)) {
                titleText = extras_.getString(TITLE_TEXT_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    @Override
    public void requestUserInfo() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PersonHome_.super.requestUserInfo();
            }

        }
        );
    }

    @Override
    public void uiThread(final UserInfo info) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PersonHome_.super.uiThread(info);
            }

        }
        );
    }

    @Override
    public void selectForUser(final String userCode) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    PersonHome_.super.selectForUser(userCode);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PersonHome_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PersonHome_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PersonHome_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PersonHome_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public PersonHome_.IntentBuilder_ mUserCode(String mUserCode) {
            intent_.putExtra(M_USER_CODE_EXTRA, mUserCode);
            return this;
        }

        public PersonHome_.IntentBuilder_ titleText(String titleText) {
            intent_.putExtra(TITLE_TEXT_EXTRA, titleText);
            return this;
        }

    }

}
