//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//

package com.yxst.epic.yixin.push.rest;

import java.nio.charset.Charset;
import java.util.HashMap;

import org.springframework.http.HttpMethod;
import org.springframework.http.converter.StringHttpMessageConverter;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public final class Msg implements IMsg {

	private RestTemplate restTemplate;
	private String rootUrl;

	private RestErrorHandler restErrorHandler;

	public Msg(String rootUrl) {
		restTemplate = new RestTemplate();
		// rootUrl = "http://115.29.107.77:8090";
		this.rootUrl = rootUrl;
		restTemplate.getMessageConverters().add(
				new StringHttpMessageConverter(Charset.defaultCharset()));
	}

	@Override
	public RestTemplate getRestTemplate() {
		return restTemplate;
	}

	@Override
	public void setRestTemplate(RestTemplate restTemplate) {
		this.restTemplate = restTemplate;
	}

	public RestErrorHandler getRestErrorHandler() {
		return restErrorHandler;
	}

	public void setRestErrorHandler(RestErrorHandler restErrorHandler) {
		this.restErrorHandler = restErrorHandler;
	}

	@Override
	public String msg(String k, int m) {
		HashMap<String, Object> urlVariables = new HashMap<String, Object>();
		urlVariables.put("k", k);
		urlVariables.put("m", m);
		try {
			return restTemplate.exchange(
					rootUrl.concat("/1/msg/get?k={k}&m={m}"), HttpMethod.GET,
					null, String.class, urlVariables).getBody();
		} catch (RestClientException e) {
			if (restErrorHandler != null) {
				restErrorHandler.onRestClientExceptionThrown(e);
				return null;
			} else {
				throw e;
			}
		}
	}

}
