//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//

package com.yxst.epic.yixin.push.rest;

import java.nio.charset.Charset;
import java.util.HashMap;

import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.StringHttpMessageConverter;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public final class Push implements IPush {

	private RestTemplate restTemplate;
	private String rootUrl;

	private RestErrorHandler restErrorHandler;

	public Push(String rootUrl) {
		restTemplate = new RestTemplate();
		// rootUrl = "http://115.29.107.77:8091";
		this.rootUrl = rootUrl;
		restTemplate.getMessageConverters().add(
				new StringHttpMessageConverter(Charset.defaultCharset()));
	}

	@Override
	public RestTemplate getRestTemplate() {
		return restTemplate;
	}

	@Override
	public void setRestTemplate(RestTemplate restTemplate) {
		this.restTemplate = restTemplate;
	}

	public RestErrorHandler getRestErrorHandler() {
		return restErrorHandler;
	}

	public void setRestErrorHandler(RestErrorHandler restErrorHandler) {
		this.restErrorHandler = restErrorHandler;
	}

	@Override
	public String push(String key, long expire, String msg) {
		HttpEntity<String> requestEntity = new HttpEntity<String>(msg);
		HashMap<String, Object> urlVariables = new HashMap<String, Object>();
		urlVariables.put("expire", expire);
		urlVariables.put("key", key);
		try {
			return restTemplate
					.exchange(
							rootUrl.concat("/1/admin/push/private?key={key}&expire={expire}"),
							HttpMethod.POST, requestEntity, String.class,
							urlVariables).getBody();
		} catch (RestClientException e) {
			if (restErrorHandler != null) {
				restErrorHandler.onRestClientExceptionThrown(e);
				return null;
			} else {
				throw e;
			}
		}
	}

}
