//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.picture;

import java.io.Serializable;
import java.util.ArrayList;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.view.ViewPager;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import com.miicaa.home.ui.photoGrid.PictureSelectView;
import com.miicaa.utils.fileselect.BrowseFileFootView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PhotoCheck_
    extends PhotoCheck
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String NAME_EXTRA = "name";
    public final static String NAMES_EXTRA = "names";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_photo_check);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        afterInject();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PhotoCheck_.IntentBuilder_ intent(Context context) {
        return new PhotoCheck_.IntentBuilder_(context);
    }

    public static PhotoCheck_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PhotoCheck_.IntentBuilder_(fragment);
    }

    public static PhotoCheck_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PhotoCheck_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        viewPager = ((ViewPager) hasViews.findViewById(id.photo_check_pager));
        title = ((TextView) hasViews.findViewById(id.title));
        backButton = ((Button) hasViews.findViewById(id.big_picture_back_button));
        pictureSlectView = ((PictureSelectView) hasViews.findViewById(id.selectView));
        footView = ((BrowseFileFootView) hasViews.findViewById(id.footView));
        saveButton = ((Button) hasViews.findViewById(id.save_big_picture));
        headView = ((RelativeLayout) hasViews.findViewById(id.headView));
        {
            View view = hasViews.findViewById(id.big_picture_back_button);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PhotoCheck_.this.backButtonClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.save_big_picture);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PhotoCheck_.this.saveButtonClick();
                    }

                }
                );
            }
        }
        afterViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(NAME_EXTRA)) {
                name = extras_.getString(NAME_EXTRA);
            }
            if (extras_.containsKey(NAMES_EXTRA)) {
                names = extras_.getStringArrayList(NAMES_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PhotoCheck_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PhotoCheck_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PhotoCheck_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PhotoCheck_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public PhotoCheck_.IntentBuilder_ name(String name) {
            intent_.putExtra(NAME_EXTRA, name);
            return this;
        }

        public PhotoCheck_.IntentBuilder_ names(ArrayList<String> names) {
            intent_.putExtra(NAMES_EXTRA, ((Serializable) names));
            return this;
        }

    }

}
