//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.perferences;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;

public final class GuideBgPerf_
    extends SharedPreferencesHelper
{

    private Context context_;

    public GuideBgPerf_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_GuideBgPerf"), 0));
        this.context_ = context;
    }

    public GuideBgPerf_.GuideBgPerfEditor_ edit() {
        return new GuideBgPerf_.GuideBgPerfEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public BooleanPrefField showBageView() {
        return booleanField("showBageView", false);
    }

    public BooleanPrefField showBg() {
        return booleanField("showBg", false);
    }

    public final static class GuideBgPerfEditor_
        extends EditorHelper<GuideBgPerf_.GuideBgPerfEditor_>
    {


        GuideBgPerfEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public BooleanPrefEditorField<GuideBgPerf_.GuideBgPerfEditor_> showBageView() {
            return booleanField("showBageView");
        }

        public BooleanPrefEditorField<GuideBgPerf_.GuideBgPerfEditor_> showBg() {
            return booleanField("showBg");
        }

    }

}
