//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.perferences;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.IntPrefEditorField;
import org.androidannotations.api.sharedpreferences.IntPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;

public final class MiicaaAuthorityPerf_
    extends SharedPreferencesHelper
{

    private Context context_;

    public MiicaaAuthorityPerf_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_MiicaaAuthorityPerf"), 0));
        this.context_ = context;
    }

    public MiicaaAuthorityPerf_.MiicaaAuthorityPerfEditor_ edit() {
        return new MiicaaAuthorityPerf_.MiicaaAuthorityPerfEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public IntPrefField approveProcessAuth() {
        return intField("approveProcessAuth", 2);
    }

    public IntPrefField photoAuthority() {
        return intField("photoAuthority", 2);
    }

    public IntPrefField subTaskAuth() {
        return intField("subTaskAuth", 2);
    }

    public final static class MiicaaAuthorityPerfEditor_
        extends EditorHelper<MiicaaAuthorityPerf_.MiicaaAuthorityPerfEditor_>
    {


        MiicaaAuthorityPerfEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public IntPrefEditorField<MiicaaAuthorityPerf_.MiicaaAuthorityPerfEditor_> approveProcessAuth() {
            return intField("approveProcessAuth");
        }

        public IntPrefEditorField<MiicaaAuthorityPerf_.MiicaaAuthorityPerfEditor_> photoAuthority() {
            return intField("photoAuthority");
        }

        public IntPrefEditorField<MiicaaAuthorityPerf_.MiicaaAuthorityPerfEditor_> subTaskAuth() {
            return intField("subTaskAuth");
        }

    }

}
