//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.menu;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.CheckBox;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class BaseScreenView_
    extends BaseScreenView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    public BaseScreenView_(Context context) {
        super(context);
        init_();
    }

    public BaseScreenView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public BaseScreenView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static BaseScreenView build(Context context) {
        BaseScreenView_ instance = new BaseScreenView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.approval_screen, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        afterInject();
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static BaseScreenView build(Context context, AttributeSet attrs) {
        BaseScreenView_ instance = new BaseScreenView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static BaseScreenView build(Context context, AttributeSet attrs, int defStyle) {
        BaseScreenView_ instance = new BaseScreenView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        contentview = ((CheckBox) hasViews.findViewById(id.contentText));
        {
            View view = hasViews.findViewById(id.contentText);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BaseScreenView_.this.scrrenClick(view);
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void click_(final View v) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                BaseScreenView_.super.click_(v);
            }

        }
        );
    }

}
