//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.photoGrid;

import java.io.Serializable;
import java.util.ArrayList;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.support.v4.view.ViewPager;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ScanerPhotoActivity_
    extends ScanerPhotoActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String PHOTOS_EXTRA = "photos";
    public final static String PHOTO_EXTRA = "photo";
    public final static String PAGE_NUM_EXTRA = "pageNum";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.scaner_photo);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        afterInject();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ScanerPhotoActivity_.IntentBuilder_ intent(Context context) {
        return new ScanerPhotoActivity_.IntentBuilder_(context);
    }

    public static ScanerPhotoActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ScanerPhotoActivity_.IntentBuilder_(fragment);
    }

    public static ScanerPhotoActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ScanerPhotoActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        viewPager = ((ViewPager) hasViews.findViewById(id.photo_check_pager));
        saveButton = ((Button) hasViews.findViewById(id.save_big_picture));
        titleText = ((TextView) hasViews.findViewById(id.title));
        backButton = ((Button) hasViews.findViewById(id.big_picture_back_button));
        {
            View view = hasViews.findViewById(id.big_picture_back_button);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ScanerPhotoActivity_.this.backClick();
                    }

                }
                );
            }
        }
        aferView();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(PHOTOS_EXTRA)) {
                photos = extras_.getParcelableArrayList(PHOTOS_EXTRA);
            }
            if (extras_.containsKey(PHOTO_EXTRA)) {
                photo = extras_.getParcelable(PHOTO_EXTRA);
            }
            if (extras_.containsKey(PAGE_NUM_EXTRA)) {
                pageNum = extras_.getInt(PAGE_NUM_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ScanerPhotoActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ScanerPhotoActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ScanerPhotoActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ScanerPhotoActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public ScanerPhotoActivity_.IntentBuilder_ photos(ArrayList<Bitmap> photos) {
            intent_.putExtra(PHOTOS_EXTRA, ((Serializable) photos));
            return this;
        }

        public ScanerPhotoActivity_.IntentBuilder_ photo(Bitmap photo) {
            intent_.putExtra(PHOTO_EXTRA, photo);
            return this;
        }

        public ScanerPhotoActivity_.IntentBuilder_ pageNum(int pageNum) {
            intent_.putExtra(PAGE_NUM_EXTRA, pageNum);
            return this;
        }

    }

}
