//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.base.share.select;

import android.content.Context;

public final class SelectKindsAdapter_
    extends SelectKindsAdapter
{

    private Context context_;

    private SelectKindsAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static SelectKindsAdapter_ getInstance_(Context context) {
        return new SelectKindsAdapter_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
