//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.home;

import android.content.Context;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.GridView;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class MatterScreenView_
    extends MatterScreenView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public MatterScreenView_(Context context) {
        super(context);
        init_();
    }

    public MatterScreenView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public MatterScreenView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static MatterScreenView build(Context context) {
        MatterScreenView_ instance = new MatterScreenView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.matter_screen_view, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        inflater = ((LayoutInflater) getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE));
        afterInject();
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static MatterScreenView build(Context context, AttributeSet attrs) {
        MatterScreenView_ instance = new MatterScreenView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static MatterScreenView build(Context context, AttributeSet attrs, int defStyle) {
        MatterScreenView_ instance = new MatterScreenView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        oneRowLayout = ((LinearLayout) hasViews.findViewById(id.oneRowLayout));
        oneRowBtn = ((ImageButton) hasViews.findViewById(id.oneRowBtn));
        oneRowGrid = ((GridView) hasViews.findViewById(id.oneRowGrid));
        {
            View view = hasViews.findViewById(id.oneRowBtn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MatterScreenView_.this.oneRowClick();
                    }

                }
                );
            }
        }
        afterViews();
    }

}
