//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.home;

import java.io.Serializable;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class TestActivity_
    extends TestActivity
    implements HasViews
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String LONGITUDE_EXTRA = "longitude";
    public final static String LOCATION_STR_EXTRA = "locationStr";
    public final static String LATITUDE_EXTRA = "latitude";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static TestActivity_.IntentBuilder_ intent(Context context) {
        return new TestActivity_.IntentBuilder_(context);
    }

    public static TestActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new TestActivity_.IntentBuilder_(fragment);
    }

    public static TestActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new TestActivity_.IntentBuilder_(supportFragment);
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(LONGITUDE_EXTRA)) {
                longitude = ((Double) extras_.getSerializable(LONGITUDE_EXTRA));
            }
            if (extras_.containsKey(LOCATION_STR_EXTRA)) {
                locationStr = extras_.getString(LOCATION_STR_EXTRA);
            }
            if (extras_.containsKey(LATITUDE_EXTRA)) {
                latitude = ((Double) extras_.getSerializable(LATITUDE_EXTRA));
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, TestActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, TestActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, TestActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public TestActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public TestActivity_.IntentBuilder_ longitude(Double longitude) {
            intent_.putExtra(LONGITUDE_EXTRA, ((Serializable) longitude));
            return this;
        }

        public TestActivity_.IntentBuilder_ locationStr(String locationStr) {
            intent_.putExtra(LOCATION_STR_EXTRA, locationStr);
            return this;
        }

        public TestActivity_.IntentBuilder_ latitude(Double latitude) {
            intent_.putExtra(LATITUDE_EXTRA, ((Serializable) latitude));
            return this;
        }

    }

}
