//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.view;

import android.content.Context;
import android.content.res.Resources;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.miicaa.home.R.dimen;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import com.miicaa.home.ui.picture.PhotoView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ChatItemImgsView_
    extends ChatItemImgsView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public ChatItemImgsView_(Context context) {
        super(context);
        init_();
    }

    public static ChatItemImgsView build(Context context) {
        ChatItemImgsView_ instance = new ChatItemImgsView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.list_item_chat_item_imgs, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        {
            OnViewChangedNotifier.registerOnViewChangedListener(this);
            Resources resources_ = getContext().getResources();
            size = resources_.getDimensionPixelOffset(dimen.icon_size_small);
        }
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ivIcon = ((ImageView) hasViews.findViewById(id.ivIcon));
        tvName = ((TextView) hasViews.findViewById(id.tvName));
        tvTime = ((TextView) hasViews.findViewById(id.tv_time));
        mLayoutLoading = ((LinearLayout) hasViews.findViewById(id.layout_loading));
        mPhotoView = ((PhotoView) hasViews.findViewById(id.iv_photoview));
        mProgressBar = ((ProgressBar) hasViews.findViewById(id.pbloading));
        mTvPercennt = ((TextView) hasViews.findViewById(id.tv_percent));
    }

}
