//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.view;

import android.content.Context;
import android.content.res.Resources;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.miicaa.home.R.dimen;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ChatItemApp102View_
    extends ChatItemApp102View
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public ChatItemApp102View_(Context context) {
        super(context);
        init_();
    }

    public static ChatItemApp102View build(Context context) {
        ChatItemApp102View_ instance = new ChatItemApp102View_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.list_item_chat_app_102, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        {
            OnViewChangedNotifier.registerOnViewChangedListener(this);
            Resources resources_ = getContext().getResources();
            size = resources_.getDimensionPixelOffset(dimen.icon_size_small);
        }
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ivIcon = ((ImageView) hasViews.findViewById(id.ivIcon));
        tvTime = ((TextView) hasViews.findViewById(id.tv_time));
        tvName = ((TextView) hasViews.findViewById(id.tvName));
        gridOperation = ((WrapContentHeightGridView) hasViews.findViewById(id.gridOperation));
        listBody = ((WrapContentHeightListView) hasViews.findViewById(id.listBody));
        layoutHead = ((LinearLayout) hasViews.findViewById(id.layoutHead));
        {
            View view = hasViews.findViewById(id.iv_icon);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatItemApp102View_.this.onClickIcon(view);
                    }

                }
                );
            }
        }
        afterViews();
    }

}
