//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.view;

import android.content.Context;
import android.content.res.Resources;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.miicaa.home.R.dimen;
import com.miicaa.home.R.drawable;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ChatItemVoiceToView_
    extends ChatItemVoiceToView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public ChatItemVoiceToView_(Context context) {
        super(context);
        init_();
    }

    public static ChatItemVoiceToView build(Context context) {
        ChatItemVoiceToView_ instance = new ChatItemVoiceToView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.list_item_chatto_voice, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        {
            OnViewChangedNotifier.registerOnViewChangedListener(this);
            Resources resources_ = getContext().getResources();
            size = resources_.getDimensionPixelOffset(dimen.icon_size_small);
            chatto_voice = resources_.getDrawable(drawable.chatto_voice_playing);
            chatto_voice_playing = resources_.getDrawable(drawable.chatto_voice);
        }
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tvName = ((TextView) hasViews.findViewById(id.tvName));
        tvTime = ((TextView) hasViews.findViewById(id.tv_time));
        ivIcon = ((ImageView) hasViews.findViewById(id.ivIcon));
        tvVoiceLenght = ((TextView) hasViews.findViewById(id.tvVoiceLenght));
        statusSending = ((ProgressBar) hasViews.findViewById(id.statusSending));
        ivVoice = ((ImageView) hasViews.findViewById(id.ivVoice));
        ivStatusError = ((ImageView) hasViews.findViewById(id.ivStatusError));
        {
            View view = hasViews.findViewById(id.ivStatusError);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatItemVoiceToView_.this.onClickIvStatusError();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.layoutContent);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatItemVoiceToView_.this.onClickLayoutContent();
                    }

                }
                );
            }
        }
    }

}
