//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.view;

import android.content.Context;
import android.content.res.Resources;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.miicaa.home.R.dimen;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import com.miicaa.home.R.string;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ChatItemImgToView_
    extends ChatItemImgToView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public ChatItemImgToView_(Context context) {
        super(context);
        init_();
    }

    public static ChatItemImgToView build(Context context) {
        ChatItemImgToView_ instance = new ChatItemImgToView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.list_item_chat_item_img_to, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        {
            OnViewChangedNotifier.registerOnViewChangedListener(this);
            Resources resources_ = getContext().getResources();
            urlFormat = resources_.getString(string.format_url_download_image2);
            size = resources_.getDimensionPixelOffset(dimen.icon_size_small);
            ivMaxSize = resources_.getDimensionPixelOffset(dimen.chat_item_img_to_iv_maxSize);
        }
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tvName = ((TextView) hasViews.findViewById(id.tvName));
        tvTime = ((TextView) hasViews.findViewById(id.tv_time));
        ivIcon = ((ImageView) hasViews.findViewById(id.ivIcon));
        tvUploadPercent = ((TextView) hasViews.findViewById(id.tvUploadPercent));
        layoutProgress = ((View) hasViews.findViewById(id.layoutProgress));
        pbUploadStatus = ((ProgressBar) hasViews.findViewById(id.pbUploadStatus));
        ivImg = ((ImageView) hasViews.findViewById(id.ivImg));
        pbSendingStatus = ((ProgressBar) hasViews.findViewById(id.pbSendingStatus));
        ivStatusError = ((ImageView) hasViews.findViewById(id.ivStatusError));
        {
            View view = hasViews.findViewById(id.ivStatusError);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatItemImgToView_.this.onClickIvStatusError();
                    }

                }
                );
            }
        }
    }

}
