//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.pay;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class BillDetailActivity_
    extends BillDetailActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String JSON_EXTRA = "json";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.layout_pay_bill_detail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        initData();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static BillDetailActivity_.IntentBuilder_ intent(Context context) {
        return new BillDetailActivity_.IntentBuilder_(context);
    }

    public static BillDetailActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new BillDetailActivity_.IntentBuilder_(fragment);
    }

    public static BillDetailActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new BillDetailActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        headImg = ((ImageView) hasViews.findViewById(id.bill_detail_img));
        useTime = ((TextView) hasViews.findViewById(id.bill_detail_useTime));
        fivePrice = ((TextView) hasViews.findViewById(id.bill_detail_five_price));
        normalPrice = ((TextView) hasViews.findViewById(id.bill_detail_normal_price));
        trandeTime = ((TextView) hasViews.findViewById(id.bill_detail_tradeTime));
        normalLength = ((TextView) hasViews.findViewById(id.bill_detail_normal_length));
        fiveLenght = ((TextView) hasViews.findViewById(id.bill_detail_five_length));
        expTime = ((TextView) hasViews.findViewById(id.bill_detail_expTime));
        cancel = ((Button) hasViews.findViewById(id.pay_cancleButton));
        orderId = ((TextView) hasViews.findViewById(id.bill_detail_orderid));
        title = ((TextView) hasViews.findViewById(id.pay_headTitle));
        fiveTitle = ((TextView) hasViews.findViewById(id.bill_detail_five_title));
        normalTitle = ((TextView) hasViews.findViewById(id.bill_detail_normal_title));
        label = ((TextView) hasViews.findViewById(id.bill_detail_label));
        name = ((TextView) hasViews.findViewById(id.bill_detail_name));
        total = ((TextView) hasViews.findViewById(id.bill_detail_total));
        state = ((TextView) hasViews.findViewById(id.bill_detail_state));
        {
            View view = hasViews.findViewById(id.pay_cancleButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BillDetailActivity_.this.cancel();
                    }

                }
                );
            }
        }
        initUI();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(JSON_EXTRA)) {
                json = extras_.getString(JSON_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, BillDetailActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, BillDetailActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, BillDetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public BillDetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public BillDetailActivity_.IntentBuilder_ json(String json) {
            intent_.putExtra(JSON_EXTRA, json);
            return this;
        }

    }

}
