//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.pay;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class BuyFivePackageActivity_
    extends BuyFivePackageActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String ACCOUNTMONEY_EXTRA = "accountmoney";
    public final static String END_TIME_EXTRA = "endTime";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.layout_pay_buy_fivepackage_activity);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        initData();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static BuyFivePackageActivity_.IntentBuilder_ intent(Context context) {
        return new BuyFivePackageActivity_.IntentBuilder_(context);
    }

    public static BuyFivePackageActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new BuyFivePackageActivity_.IntentBuilder_(fragment);
    }

    public static BuyFivePackageActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new BuyFivePackageActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        back = ((Button) hasViews.findViewById(id.pay_cancleButton));
        timeLenght = ((TextView) hasViews.findViewById(id.buy_fivetimelength));
        moneyTotal = ((TextView) hasViews.findViewById(id.buy_money_total));
        tlpFivePackage = ((TableLayoutPackageView) hasViews.findViewById(id.pay_package_five));
        countMinus = ((ImageButton) hasViews.findViewById(id.buy_count_minus));
        introduce = ((TextView) hasViews.findViewById(id.buy_protocol_introduce));
        checkbox = ((CheckBox) hasViews.findViewById(id.buy_protocol_checkbox));
        countEdit = ((EditText) hasViews.findViewById(id.buy_count_edit));
        headTitle = ((TextView) hasViews.findViewById(id.pay_headTitle));
        {
            View view = hasViews.findViewById(id.buy_count_plus);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BuyFivePackageActivity_.this.countPlus();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.buy_count_minus);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BuyFivePackageActivity_.this.countMinus();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.pay_cancleButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BuyFivePackageActivity_.this.cancel();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.buy_commit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BuyFivePackageActivity_.this.commit();
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) hasViews.findViewById(id.buy_count_edit));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                    }

                    @Override
                    public void afterTextChanged(Editable s) {
                        BuyFivePackageActivity_.this.countChange(s);
                    }

                }
                );
            }
        }
        initUI();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(ACCOUNTMONEY_EXTRA)) {
                accountmoney = extras_.getDouble(ACCOUNTMONEY_EXTRA);
            }
            if (extras_.containsKey(END_TIME_EXTRA)) {
                endTime = extras_.getLong(END_TIME_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, BuyFivePackageActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, BuyFivePackageActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, BuyFivePackageActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public BuyFivePackageActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public BuyFivePackageActivity_.IntentBuilder_ accountmoney(double accountmoney) {
            intent_.putExtra(ACCOUNTMONEY_EXTRA, accountmoney);
            return this;
        }

        public BuyFivePackageActivity_.IntentBuilder_ endTime(long endTime) {
            intent_.putExtra(END_TIME_EXTRA, endTime);
            return this;
        }

    }

}
