//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.pay;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PayMentActivity_
    extends PayMentActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String FIVE_JSON_EXTRA = "fiveJSON";
    public final static String PACKAGE_JSON_EXTRA = "packageJSON";
    public final static String PACKAGE_VALUE_EXTRA = "packageValue";
    public final static String M_COUNT_EXTRA = "mCount";
    public final static String M_TIME_LENGTH_EXTRA = "mTimeLength";
    public final static String TYPE_EXTRA = "type";
    public final static String M_TOTAL_EXTRA = "mTotal";
    public final static String FIVE_VALUE_EXTRA = "fiveValue";
    public final static String ACCOUNTMONEY_EXTRA = "accountmoney";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.layout_pay_payment_activity);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        initData();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PayMentActivity_.IntentBuilder_ intent(Context context) {
        return new PayMentActivity_.IntentBuilder_(context);
    }

    public static PayMentActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PayMentActivity_.IntentBuilder_(fragment);
    }

    public static PayMentActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PayMentActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        accountMoneyTotal = ((TextView) hasViews.findViewById(id.payment_account_money));
        headTitle = ((TextView) hasViews.findViewById(id.pay_headTitle));
        moneyTotal = ((TextView) hasViews.findViewById(id.payment_money));
        convertView = ((View) hasViews.findViewById(id.convertView));
        back = ((Button) hasViews.findViewById(id.pay_cancleButton));
        {
            View view = hasViews.findViewById(id.pay_cancleButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PayMentActivity_.this.cancel();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.payment_commit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PayMentActivity_.this.commit();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.payment_recharge);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PayMentActivity_.this.recharge();
                    }

                }
                );
            }
        }
        initUI();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(FIVE_JSON_EXTRA)) {
                fiveJSON = extras_.getString(FIVE_JSON_EXTRA);
            }
            if (extras_.containsKey(PACKAGE_JSON_EXTRA)) {
                packageJSON = extras_.getString(PACKAGE_JSON_EXTRA);
            }
            if (extras_.containsKey(PACKAGE_VALUE_EXTRA)) {
                packageValue = extras_.getDouble(PACKAGE_VALUE_EXTRA);
            }
            if (extras_.containsKey(M_COUNT_EXTRA)) {
                mCount = extras_.getInt(M_COUNT_EXTRA);
            }
            if (extras_.containsKey(M_TIME_LENGTH_EXTRA)) {
                mTimeLength = extras_.getInt(M_TIME_LENGTH_EXTRA);
            }
            if (extras_.containsKey(TYPE_EXTRA)) {
                type = extras_.getString(TYPE_EXTRA);
            }
            if (extras_.containsKey(M_TOTAL_EXTRA)) {
                mTotal = extras_.getDouble(M_TOTAL_EXTRA);
            }
            if (extras_.containsKey(FIVE_VALUE_EXTRA)) {
                fiveValue = extras_.getDouble(FIVE_VALUE_EXTRA);
            }
            if (extras_.containsKey(ACCOUNTMONEY_EXTRA)) {
                accountmoney = extras_.getDouble(ACCOUNTMONEY_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PayMentActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PayMentActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PayMentActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PayMentActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public PayMentActivity_.IntentBuilder_ fiveJSON(String fiveJSON) {
            intent_.putExtra(FIVE_JSON_EXTRA, fiveJSON);
            return this;
        }

        public PayMentActivity_.IntentBuilder_ packageJSON(String packageJSON) {
            intent_.putExtra(PACKAGE_JSON_EXTRA, packageJSON);
            return this;
        }

        public PayMentActivity_.IntentBuilder_ packageValue(double packageValue) {
            intent_.putExtra(PACKAGE_VALUE_EXTRA, packageValue);
            return this;
        }

        public PayMentActivity_.IntentBuilder_ mCount(int mCount) {
            intent_.putExtra(M_COUNT_EXTRA, mCount);
            return this;
        }

        public PayMentActivity_.IntentBuilder_ mTimeLength(int mTimeLength) {
            intent_.putExtra(M_TIME_LENGTH_EXTRA, mTimeLength);
            return this;
        }

        public PayMentActivity_.IntentBuilder_ type(String type) {
            intent_.putExtra(TYPE_EXTRA, type);
            return this;
        }

        public PayMentActivity_.IntentBuilder_ mTotal(double mTotal) {
            intent_.putExtra(M_TOTAL_EXTRA, mTotal);
            return this;
        }

        public PayMentActivity_.IntentBuilder_ fiveValue(double fiveValue) {
            intent_.putExtra(FIVE_VALUE_EXTRA, fiveValue);
            return this;
        }

        public PayMentActivity_.IntentBuilder_ accountmoney(double accountmoney) {
            intent_.putExtra(ACCOUNTMONEY_EXTRA, accountmoney);
            return this;
        }

    }

}
