//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.pay;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.MotionEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.View.OnTouchListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ReceiptOpeningActivity_
    extends ReceiptOpeningActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String M_CURRENT_USEABLE_EXTRA = "mCurrentUseable";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.layout_pay_receipt_opening);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        initData();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ReceiptOpeningActivity_.IntentBuilder_ intent(Context context) {
        return new ReceiptOpeningActivity_.IntentBuilder_(context);
    }

    public static ReceiptOpeningActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ReceiptOpeningActivity_.IntentBuilder_(fragment);
    }

    public static ReceiptOpeningActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ReceiptOpeningActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        phone = ((EditText) hasViews.findViewById(id.receipt_opening_phone));
        header = ((EditText) hasViews.findViewById(id.receipt_opening_header));
        useMoney = ((TextView) hasViews.findViewById(id.receipt_opening_useMoney));
        back = ((Button) hasViews.findViewById(id.pay_cancleButton));
        commit = ((Button) hasViews.findViewById(id.pay_commitButton));
        people = ((TextView) hasViews.findViewById(id.receipt_opening_people));
        headTitle = ((TextView) hasViews.findViewById(id.pay_headTitle));
        address = ((EditText) hasViews.findViewById(id.receipt_opening_address));
        postcode = ((EditText) hasViews.findViewById(id.receipt_opening_postcode));
        email = ((EditText) hasViews.findViewById(id.receipt_opening_email));
        money = ((EditText) hasViews.findViewById(id.receipt_opening_money));
        {
            View view = hasViews.findViewById(id.pay_cancleButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ReceiptOpeningActivity_.this.cancel();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.pay_commitButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ReceiptOpeningActivity_.this.commit();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.topView);
            if (view!= null) {
                view.setOnTouchListener(new OnTouchListener() {


                    @Override
                    public boolean onTouch(View view, MotionEvent event) {
                        return ReceiptOpeningActivity_.this.touch(event, view);
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) hasViews.findViewById(id.receipt_opening_money));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                    }

                    @Override
                    public void afterTextChanged(Editable s) {
                        ReceiptOpeningActivity_.this.onBefore(s);
                    }

                }
                );
            }
        }
        initUI();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(M_CURRENT_USEABLE_EXTRA)) {
                mCurrentUseable = extras_.getDouble(M_CURRENT_USEABLE_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ReceiptOpeningActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ReceiptOpeningActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ReceiptOpeningActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ReceiptOpeningActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public ReceiptOpeningActivity_.IntentBuilder_ mCurrentUseable(double mCurrentUseable) {
            intent_.putExtra(M_CURRENT_USEABLE_EXTRA, mCurrentUseable);
            return this;
        }

    }

}
