package com.yxst.epic.yixin.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEMBER.
 */
public class Member {

    private Long id;
    private String Uid;
    private String UserName;
    private String NickName;
    private String PYInitial;
    private String PYQuanPin;
    private String HeadImgUrl;
    private Integer Sex;
    private String Signature;
    private String RemarkName;
    private String RemarkPYInitial;
    private String RemarkPYQuanPin;
    private String Province;
    private String City;
    private String Alias;
    private String StarFriend;

    public Member() {
    }

    public Member(Long id) {
        this.id = id;
    }

    public Member(Long id, String Uid, String UserName, String NickName, String PYInitial, String PYQuanPin, String HeadImgUrl, Integer Sex, String Signature, String RemarkName, String RemarkPYInitial, String RemarkPYQuanPin, String Province, String City, String Alias, String StarFriend) {
        this.id = id;
        this.Uid = Uid;
        this.UserName = UserName;
        this.NickName = NickName;
        this.PYInitial = PYInitial;
        this.PYQuanPin = PYQuanPin;
        this.HeadImgUrl = HeadImgUrl;
        this.Sex = Sex;
        this.Signature = Signature;
        this.RemarkName = RemarkName;
        this.RemarkPYInitial = RemarkPYInitial;
        this.RemarkPYQuanPin = RemarkPYQuanPin;
        this.Province = Province;
        this.City = City;
        this.Alias = Alias;
        this.StarFriend = StarFriend;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid() {
        return Uid;
    }

    public void setUid(String Uid) {
        this.Uid = Uid;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getNickName() {
        return NickName;
    }

    public void setNickName(String NickName) {
        this.NickName = NickName;
    }

    public String getPYInitial() {
        return PYInitial;
    }

    public void setPYInitial(String PYInitial) {
        this.PYInitial = PYInitial;
    }

    public String getPYQuanPin() {
        return PYQuanPin;
    }

    public void setPYQuanPin(String PYQuanPin) {
        this.PYQuanPin = PYQuanPin;
    }

    public String getHeadImgUrl() {
        return HeadImgUrl;
    }

    public void setHeadImgUrl(String HeadImgUrl) {
        this.HeadImgUrl = HeadImgUrl;
    }

    public Integer getSex() {
        return Sex;
    }

    public void setSex(Integer Sex) {
        this.Sex = Sex;
    }

    public String getSignature() {
        return Signature;
    }

    public void setSignature(String Signature) {
        this.Signature = Signature;
    }

    public String getRemarkName() {
        return RemarkName;
    }

    public void setRemarkName(String RemarkName) {
        this.RemarkName = RemarkName;
    }

    public String getRemarkPYInitial() {
        return RemarkPYInitial;
    }

    public void setRemarkPYInitial(String RemarkPYInitial) {
        this.RemarkPYInitial = RemarkPYInitial;
    }

    public String getRemarkPYQuanPin() {
        return RemarkPYQuanPin;
    }

    public void setRemarkPYQuanPin(String RemarkPYQuanPin) {
        this.RemarkPYQuanPin = RemarkPYQuanPin;
    }

    public String getProvince() {
        return Province;
    }

    public void setProvince(String Province) {
        this.Province = Province;
    }

    public String getCity() {
        return City;
    }

    public void setCity(String City) {
        this.City = City;
    }

    public String getAlias() {
        return Alias;
    }

    public void setAlias(String Alias) {
        this.Alias = Alias;
    }

    public String getStarFriend() {
        return StarFriend;
    }

    public void setStarFriend(String StarFriend) {
        this.StarFriend = StarFriend;
    }

}
