//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.utils.fileselect;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class BrowseFileFootView_
    extends BrowseFileFootView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public BrowseFileFootView_(Context context) {
        super(context);
        init_();
    }

    public BrowseFileFootView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public BrowseFileFootView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static BrowseFileFootView build(Context context) {
        BrowseFileFootView_ instance = new BrowseFileFootView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.browse_file_foot_view, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static BrowseFileFootView build(Context context, AttributeSet attrs) {
        BrowseFileFootView_ instance = new BrowseFileFootView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static BrowseFileFootView build(Context context, AttributeSet attrs, int defStyle) {
        BrowseFileFootView_ instance = new BrowseFileFootView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        saveBtn = ((Button) hasViews.findViewById(id.saveButton));
        moveBtn = ((Button) hasViews.findViewById(id.moveButton));
        editBtn = ((Button) hasViews.findViewById(id.editButton));
        delBtn = ((Button) hasViews.findViewById(id.delButton));
        {
            View view = hasViews.findViewById(id.moveButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BrowseFileFootView_.this.moveClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.delButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BrowseFileFootView_.this.delClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.saveButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BrowseFileFootView_.this.saveClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.editButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BrowseFileFootView_.this.editClick();
                    }

                }
                );
            }
        }
        afterView();
    }

}
