//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.base.share.industry;

import android.content.Context;

public final class IndustryAdapter_
    extends IndustryAdapter
{

    private Context context_;

    private IndustryAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static IndustryAdapter_ getInstance_(Context context) {
        return new IndustryAdapter_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
