//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.adapter;

import android.content.Context;

public final class AppListAdapter_
    extends AppListAdapter
{

    private Context context_;

    private AppListAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static AppListAdapter_ getInstance_(Context context) {
        return new AppListAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
