//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.adapter;

import android.content.Context;

public final class ChatImagesAdapter_
    extends ChatImagesAdapter
{

    private Context context_;

    private ChatImagesAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static ChatImagesAdapter_ getInstance_(Context context) {
        return new ChatImagesAdapter_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
