//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.rest.com.yxst.epic.yixin.rest;

import com.yxst.epic.yixin.rest.ServiceResult;

public class ServiceResult_Object
    extends ServiceResult<Object>
{


}
