//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.announcement;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.miicaa.base.RoundImage.CircularImage;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AnnouncementDetailActivity_
    extends AnnouncementDetailActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String JSON_STR_EXTRA = "jsonStr";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.announcement_detail_view);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        initData();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static AnnouncementDetailActivity_.IntentBuilder_ intent(Context context) {
        return new AnnouncementDetailActivity_.IntentBuilder_(context);
    }

    public static AnnouncementDetailActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new AnnouncementDetailActivity_.IntentBuilder_(fragment);
    }

    public static AnnouncementDetailActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new AnnouncementDetailActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        back = ((Button) hasViews.findViewById(id.pay_cancleButton));
        htitle = ((TextView) hasViews.findViewById(id.pay_headTitle));
        mFileLayout = ((RelativeLayout) hasViews.findViewById(id.file_layout));
        mFileCountText = ((TextView) hasViews.findViewById(id.file_count));
        littlePhoto = ((ImageView) hasViews.findViewById(id.picture));
        unit = ((TextView) hasViews.findViewById(id.unit));
        symbol = ((TextView) hasViews.findViewById(id.symbol));
        mPhotoCountText = ((TextView) hasViews.findViewById(id.photo_count));
        mPhotoLayout = ((RelativeLayout) hasViews.findViewById(id.photo_layout));
        mAttachmentLayout = ((LinearLayout) hasViews.findViewById(id.attachment_layout));
        headImg = ((CircularImage) hasViews.findViewById(id.headimg));
        title = ((TextView) hasViews.findViewById(id.title));
        content = ((TextView) hasViews.findViewById(id.content));
        keepDays = ((TextView) hasViews.findViewById(id.keepDays));
        time = ((TextView) hasViews.findViewById(id.pubtime));
        name = ((TextView) hasViews.findViewById(id.name));
        commit = ((Button) hasViews.findViewById(id.pay_commitButton));
        {
            View view = hasViews.findViewById(id.pay_cancleButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AnnouncementDetailActivity_.this.back();
                    }

                }
                );
            }
        }
        initUI();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(JSON_STR_EXTRA)) {
                jsonStr = extras_.getString(JSON_STR_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, AnnouncementDetailActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, AnnouncementDetailActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, AnnouncementDetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public AnnouncementDetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public AnnouncementDetailActivity_.IntentBuilder_ jsonStr(String jsonStr) {
            intent_.putExtra(JSON_STR_EXTRA, jsonStr);
            return this;
        }

    }

}
