//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.checkwork;

import java.util.ArrayList;
import java.util.HashMap;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedNotifier;
import org.json.JSONObject;

public final class CheckWorkActivity_
    extends CheckWorkActivity
    implements HasViews
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        inflater = ((LayoutInflater) this.getSystemService(Context.LAYOUT_INFLATER_SERVICE));
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static CheckWorkActivity_.IntentBuilder_ intent(Context context) {
        return new CheckWorkActivity_.IntentBuilder_(context);
    }

    public static CheckWorkActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new CheckWorkActivity_.IntentBuilder_(fragment);
    }

    public static CheckWorkActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new CheckWorkActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  0 :
                CheckWorkActivity_.this.onNameResult(resultCode, data);
                break;
            case  7 :
                CheckWorkActivity_.this.onSignResult(resultCode, data);
                break;
            case  1 :
                CheckWorkActivity_.this.onOrgResult(resultCode, data);
                break;
        }
    }

    @Override
    public void refreshTongjiAdapter(final ArrayList<CheckWorkTongjiContents> tongjiList) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                CheckWorkActivity_.super.refreshTongjiAdapter(tongjiList);
            }

        }
        );
    }

    @Override
    public void refreshMyAdapter(final HashMap<String, String> todayContentMap, final CheckWorkTongjiContents tongjiMap, final ArrayList<CheckWorkDetailContent> detailContents, final Long nowDateStr) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                CheckWorkActivity_.super.refreshMyAdapter(todayContentMap, tongjiMap, detailContents, nowDateStr);
            }

        }
        );
    }

    @Override
    public void refreshAllAdapter(final ArrayList<CheckWorkDetailContent> detailContents, final Long nowDateStr) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                CheckWorkActivity_.super.refreshAllAdapter(detailContents, nowDateStr);
            }

        }
        );
    }

    @Override
    public void saveAllCheckWorkContent(final JSONObject jsonObject) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    CheckWorkActivity_.super.saveAllCheckWorkContent(jsonObject);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void saveTongjiCheckWorkContent(final JSONObject jsonObject) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    CheckWorkActivity_.super.saveTongjiCheckWorkContent(jsonObject);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void saveMyCheckWorkContent(final JSONObject jsonObject) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    CheckWorkActivity_.super.saveMyCheckWorkContent(jsonObject);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, CheckWorkActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, CheckWorkActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, CheckWorkActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public CheckWorkActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
