//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.checkwork;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class EditSignBeizhuActivity_
    extends EditSignBeizhuActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String HUIXIAN_EXTRA = "huixian";
    public final static String SIGN_IN_OR_SIGN_OUT_STR_EXTRA = "signInOrSignOutStr";
    public final static String TITLE_TEXT_EXTRA = "titleText";
    public final static String M_ID_EXTRA = "mId";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_checkwork_beizhu);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static EditSignBeizhuActivity_.IntentBuilder_ intent(Context context) {
        return new EditSignBeizhuActivity_.IntentBuilder_(context);
    }

    public static EditSignBeizhuActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new EditSignBeizhuActivity_.IntentBuilder_(fragment);
    }

    public static EditSignBeizhuActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new EditSignBeizhuActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        editText = ((EditText) hasViews.findViewById(id.editText));
        zishuTextView = ((TextView) hasViews.findViewById(id.zishuTextView));
        {
            final TextView view = ((TextView) hasViews.findViewById(id.editText));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                        EditSignBeizhuActivity_.this.onTextChangesOnEditText(s, view, before, start, count);
                    }

                    @Override
                    public void afterTextChanged(Editable s) {
                    }

                }
                );
            }
        }
        afterViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(HUIXIAN_EXTRA)) {
                huixian = extras_.getString(HUIXIAN_EXTRA);
            }
            if (extras_.containsKey(SIGN_IN_OR_SIGN_OUT_STR_EXTRA)) {
                signInOrSignOutStr = extras_.getString(SIGN_IN_OR_SIGN_OUT_STR_EXTRA);
            }
            if (extras_.containsKey(TITLE_TEXT_EXTRA)) {
                titleText = extras_.getString(TITLE_TEXT_EXTRA);
            }
            if (extras_.containsKey(M_ID_EXTRA)) {
                mId = extras_.getString(M_ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, EditSignBeizhuActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, EditSignBeizhuActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, EditSignBeizhuActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public EditSignBeizhuActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public EditSignBeizhuActivity_.IntentBuilder_ huixian(String huixian) {
            intent_.putExtra(HUIXIAN_EXTRA, huixian);
            return this;
        }

        public EditSignBeizhuActivity_.IntentBuilder_ signInOrSignOutStr(String signInOrSignOutStr) {
            intent_.putExtra(SIGN_IN_OR_SIGN_OUT_STR_EXTRA, signInOrSignOutStr);
            return this;
        }

        public EditSignBeizhuActivity_.IntentBuilder_ titleText(String titleText) {
            intent_.putExtra(TITLE_TEXT_EXTRA, titleText);
            return this;
        }

        public EditSignBeizhuActivity_.IntentBuilder_ mId(String mId) {
            intent_.putExtra(M_ID_EXTRA, mId);
            return this;
        }

    }

}
