//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.checkwork;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class SignView_
    extends SignView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public SignView_(Context context) {
        super(context);
        init_();
    }

    public SignView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public SignView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static SignView build(Context context) {
        SignView_ instance = new SignView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.sign_view, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static SignView build(Context context, AttributeSet attrs) {
        SignView_ instance = new SignView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static SignView build(Context context, AttributeSet attrs, int defStyle) {
        SignView_ instance = new SignView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        imageView = ((ImageView) hasViews.findViewById(id.imageView));
        progressBar = ((ProgressBar) hasViews.findViewById(id.progressBar));
        signButton = ((Button) hasViews.findViewById(id.signBtn));
        signRemindButton = ((Button) hasViews.findViewById(id.signRemind));
        titleText = ((TextView) hasViews.findViewById(id.title));
        {
            View view = hasViews.findViewById(id.signRemind);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SignView_.this.signRemindClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.signBtn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SignView_.this.signBtnClick();
                    }

                }
                );
            }
        }
    }

}
